const OpenAI = require('openai');

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// ============================================================
// SYSTEM PROMPTS
// ============================================================

const PASS1_SYSTEM_PROMPT = `You are an expert email design analyst. Your job is to analyze a full email mockup image and extract structured information for use in HTML email template generation.

Analyze the image carefully and return ONLY a valid JSON object (no markdown, no explanation) with this exact structure:

{
  "style_descriptor": "brief description of the dominant visual style, color palette, illustration style",
  "image_assets": [
    {
      "id": "unique_snake_case_id",
      "type": "logo|illustration|screenshot|icon|banner|photo",
      "category": "structural|placeholder",
      "description": "what this image represents",
      "bbox": { "x": 0, "y": 0, "width": 0, "height": 0 },
      "suggested_prompt": "detailed generation prompt (only for placeholder category)",
      "target_size": { "width": 0, "height": 0 }
    }
  ],
  "sections": [
    { "id": "section_snake_case_id", "label": "Human readable label" }
  ],
  "text_areas": [
    {
      "id": "text_snake_case_id",
      "content": "the actual text visible in the image",
      "detected_variables": ["list of Go Template variables if detected, e.g. .Subscriber.FirstName"]
    }
  ]
}

Rules:
- "structural" category = permanent brand identity elements (logos, brand icons, navigation icons). These will be CROPPED from the mockup.
- "placeholder" category = content illustrations, photos, decorative images. These will be REGENERATED by AI. Always include "suggested_prompt" that incorporates the style_descriptor for visual consistency.
- bbox coordinates are relative to the original image dimensions (top-left origin: x=0, y=0).
- Every repeating card/item (e.g. step-1, step-2, step-3) must be listed as a SEPARATE section.
- section "footer" must always be the last entry in the sections array.
- For suggested_prompt: always append ", no text" at the end to prevent text in generated images.
- target_size for placeholder assets should reflect the actual display size in the email (typically not larger than 600px wide).
- Detect Go Template patterns: [Name]/$$Name$$/{name}/"Dear Customer" → .Subscriber.FirstName, [Email] → .Subscriber.Email, unsubscribe links → UnsubscribeURL (NO dot prefix)
- IMPORTANT: Listmonk uses {{ UnsubscribeURL }} and {{ MessageURL }} WITHOUT dot prefix. But subscriber fields use dot: {{ .Subscriber.Name }}`;

const PASS2_SYSTEM_PROMPT = `You are an expert HTML email template developer specializing in email-safe HTML for Listmonk newsletter platform.

Generate ONLY the complete HTML code, no explanations, no markdown code blocks, no text before or after the HTML.

CRITICAL RULES:
1. Use TABLE-BASED layout ONLY. Use <table>, <tr>, <td>. NEVER use <div> for layout.
2. ALL CSS must be INLINE. No external stylesheets.
3. Max-width: 600px, centered. ONE <style> tag in <head> for mobile media queries only.
4. Every major section MUST be wrapped: <table data-section-id="..." data-section-label="..."> ... </table>
5. Add HTML comment before each section: <!-- SECTION: section_id -->
6. Repeating items (step-1, step-2, step-3) must each be a SEPARATE section with unique data-section-id.
7. Section "footer" MUST be the LAST section and MUST contain {{ UnsubscribeURL }}.
8. For structural images (logos): use the provided Listmonk URL in src. Add border="0", display:block, appropriate alt text.
9. For placeholder images: use the provided Listmonk URL in src. Add these EXACT attributes:
   - data-asset-id="[asset_id_from_analysis]"
   - data-regeneratable="true"
   - appropriate alt, width, height, style="display:block;"
10. Replace ALL placeholder text patterns with Listmonk Go Template variables:
    - [Name]/$$Name$$/"Dear Customer" → {{ .Subscriber.FirstName }}
    - [Email]/$$Email$$ → {{ .Subscriber.Email }}
    - Unsubscribe link text/button href → {{ UnsubscribeURL }} (NO dot prefix!)
    - View in browser link href → {{ MessageURL }} (NO dot prefix!)
11. ALWAYS include {{ UnsubscribeURL }} in the footer section.
12. CRITICAL: {{ UnsubscribeURL }}, {{ MessageURL }}, and {{ TrackView }} are FUNCTIONS, written WITHOUT a dot prefix. But subscriber fields like {{ .Subscriber.Email }} DO use dot prefix.
13. HTML must be valid and renderable in all major email clients (Gmail, Outlook, Apple Mail).
14. Use web-safe fonts with fallbacks. Prefer: Arial, Georgia, or similar.

Return ONLY the complete HTML document starting with <!DOCTYPE html>.`;

// ============================================================
// HELPER: sleep for retry backoff
// ============================================================
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// ============================================================
// PASS 1 — Image Analysis
// ============================================================

/**
 * Analisis gambar mockup email dan ekstrak struktur JSON.
 * @param {string} imageBase64 - base64 encoded image
 * @param {string} mimeType - 'image/jpeg' atau 'image/png'
 * @returns {Promise<object>} parsed analysis result
 */
const analyzeImage = async (imageBase64, mimeType = 'image/jpeg') => {
  const attempt = async () => {
    const response = await openai.chat.completions.create({
      model: 'gpt-5.4',
      max_completion_tokens: 4096,
      messages: [
        { role: 'system', content: PASS1_SYSTEM_PROMPT },
        {
          role: 'user',
          content: [
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${imageBase64}`,
                detail: 'high',
              },
            },
            {
              type: 'text',
              text: 'Analyze this email mockup and return the JSON structure as specified. Be precise with bounding box coordinates.',
            },
          ],
        },
      ],
    });

    const content = response.choices[0]?.message?.content || '';

    // Parse JSON — strip any accidental markdown wrapping
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('AI tidak mengembalikan JSON yang valid dari Pass 1.');
    }

    return JSON.parse(jsonMatch[0]);
  };

  try {
    return await attempt();
  } catch (err) {
    console.warn('[VisionClient] Pass 1 attempt 1 gagal, retry...', err.message);
    await sleep(2000);
    return await attempt(); // retry 1x
  }
};

// ============================================================
// PASS 2 — HTML Generation
// ============================================================

/**
 * Generate HTML template dari hasil analisis dan asset URLs.
 * @param {string} imageBase64 - base64 gambar original (konteks visual)
 * @param {string} mimeType
 * @param {object} analysisResult - hasil dari analyzeImage
 * @param {object} assetUrlMap - { assetId: listmonkUrl }
 * @returns {Promise<string>} HTML string
 */
const generateHTML = async (imageBase64, mimeType = 'image/jpeg', analysisResult, assetUrlMap) => {
  const assetMapText = Object.entries(assetUrlMap)
    .map(([id, url]) => `  - ${id}: ${url}`)
    .join('\n');

  const userMessage = `
Generate the complete HTML email template based on:

1. The mockup image (provided above as visual reference)
2. Analysis result:
${JSON.stringify(analysisResult, null, 2)}

3. Asset URL mapping (use these URLs for <img> src):
${assetMapText}

Generate the complete, valid HTML email template now.
`.trim();

  const attempt = async () => {
    const response = await openai.chat.completions.create({
      model: 'gpt-4.1',
      max_tokens: 8192,
      messages: [
        { role: 'system', content: PASS2_SYSTEM_PROMPT },
        {
          role: 'user',
          content: [
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${imageBase64}`,
                detail: 'high',
              },
            },
            { type: 'text', text: userMessage },
          ],
        },
      ],
    });

    const htmlContent = response.choices[0]?.message?.content || '';

    // Validasi minimal output adalah HTML
    if (!htmlContent.includes('<html') && !htmlContent.includes('<!DOCTYPE')) {
      throw new Error('AI tidak mengembalikan HTML yang valid dari Pass 2.');
    }

    // Bersihkan markdown code block jika ada (safety net)
    return htmlContent
      .replace(/^```html\n?/i, '')
      .replace(/^```\n?/, '')
      .replace(/\n?```$/, '')
      .trim();
  };

  try {
    return await attempt();
  } catch (err) {
    console.warn('[VisionClient] Pass 2 attempt 1 gagal, retry...', err.message);
    await sleep(3000);
    return await attempt(); // retry 1x
  }
};

// ============================================================
// CHAT REVISOR
// ============================================================

const CHAT_REVISOR_SYSTEM_PROMPT = `Kamu adalah spesialis HTML email template. Kamu akan menerima kode HTML email dan instruksi revisi dari user.

Tugasmu:
1. Analisis instruksi user
2. Lakukan perubahan minimal yang diperlukan pada HTML
3. Kembalikan HANYA kode HTML lengkap yang sudah direvisi, tanpa penjelasan, tanpa markdown, tanpa komentar di luar HTML

Aturan yang tidak boleh dilanggar:
- Pertahankan struktur tabel-based (jangan gunakan div untuk layout)
- Pertahankan semua inline CSS
- Jangan hapus atau ubah variabel Go Template ({{ .Subscriber.FirstName }}, {{ UnsubscribeURL }}, {{ MessageURL }}, dll) — WAJIB ada
- Jangan hapus link unsubscribe {{ UnsubscribeURL }}
- PENTING: {{ UnsubscribeURL }}, {{ MessageURL }}, {{ TrackView }} ditulis TANPA dot prefix. Tapi field subscriber pakai dot: {{ .Subscriber.Email }}
- Pertahankan semua atribut data-section-id dan data-section-label pada setiap <table> section
- Pertahankan semua atribut data-asset-id dan data-regeneratable pada setiap <img> yang regeneratable
- Max width tetap 600px
- Jangan mengosongkan src="" pada <img> kecuali diminta eksplisit oleh user
- Output HANYA HTML, mulai dari <!DOCTYPE html>`;

/**
 * Revisi HTML menggunakan GPT-4o chat.
 * @param {string} userMessage
 * @param {string} currentHtml
 * @param {Array} history - array of { role, content }
 * @returns {Promise<{ revisedHtml: string, assistantMessage: string }>}
 */
const reviseHTML = async (userMessage, currentHtml, history = []) => {
  // Batasi history: max 20 pesan (drop terlama selain system)
  const maxHistory = 20;
  const trimmedHistory = history.length > maxHistory
    ? history.slice(history.length - maxHistory)
    : history;

  const messages = [
    { role: 'system', content: CHAT_REVISOR_SYSTEM_PROMPT },
    ...trimmedHistory,
    {
      role: 'user',
      content: `Berikut kode HTML template saat ini:\n\n${currentHtml}\n\nInstruksi revisi: ${userMessage}`,
    },
  ];

  const response = await openai.chat.completions.create({
    model: 'gpt-4.1',
    max_tokens: 8192,
    messages,
  });

  const rawContent = response.choices[0]?.message?.content || '';

  // Extract HTML
  const revisedHtml = rawContent
    .replace(/^```html\n?/i, '')
    .replace(/^```\n?/, '')
    .replace(/\n?```$/, '')
    .trim();

  // Validasi
  if (!revisedHtml.includes('<html') && !revisedHtml.includes('<!DOCTYPE')) {
    throw new Error('AI gagal menghasilkan HTML yang valid dari Chat Revisor.');
  }

  return {
    revisedHtml,
    assistantMessage: '✓ Template diperbarui. Klik ↩ Undo untuk membatalkan.',
  };
};

module.exports = { analyzeImage, generateHTML, reviseHTML };
